# QUOTES CRUD

GET http://localhost:5000/quotes

###

POST http://localhost:5000/quotes
Content-Type: application/json

{
    "text": "He restores my soul",
    "authorId": 2 
}

### 

PATCH http://localhost:5000/quotes/1

###

DELETE http://localhost:5000/quotes/2

###

# --------------------------------
# AUTHORS CRUD
# --------------------------------

GET http://localhost:5000/authors

###

POST http://localhost:5000/authors
Content-Type: application/json

{
    "name": "King David"
}

###

GET http://localhost:5000/authors/1


###

# --------------------------------
# USERS CRUD
# --------------------------------

GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "Noel",
    "password": "heh3433"
}


