name: Continuous Deployment

on:
  push:
    branches: [main]
  

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code and add it to CI server
        uses: actions/checkout@v2
      
      - name: Setup render deploy action
        uses: JorgeLNJunior/render-deploy@v1.3.2
        with:
          service_id: ${{secrets.RENDER_SERVICE_ID}} # required
          api_key: ${{secrets.RENDER_API_KEY}} # required
          clear_cache: false # Clear build cache. Optional
          wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional